CREATE TABLE Artisti 
	(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	nume_scena VARCHAR(100) NOT NULL UNIQUE
	);

CREATE TABLE Albume
	(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	denumire VARCHAR(50) NOT NULL,
	an_aparitie INT
	);

CREATE TABLE Melodii
	(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	denumire VARCHAR(50) NOT NULL,
	an_aparitie INT,
	id_album BIGINT REFERENCES Albume(id)
	);


CREATE TABLE Melodii_Artisti
	(id_melodie BIGINT REFERENCES Melodii(id),
	id_artist BIGINT REFERENCES Artisti(id),
	PRIMARY KEY(id_melodie,id_artist)
	);
